// AUTO-GENERATED by `npm run gen:contracts`. Do not edit by hand.
// Source of truth: common/contracts/registry.py (Pydantic v2 models).

export type WidgetKind =
  | "combo"
  | "segmented"
  | "chip_grid"
  | "chip_list"
  | "number"
  | "slider"
  | "boolean"
  | "string"
  | "color"
  | "dict"
  | "custom";

export interface WidgetSpec {
  name: string;
  kind: WidgetKind;
  label?: string | null;
  default?: unknown;
  tooltip?: string | null;
  values?: string[] | null;
  columns?: number | null;
  searchable?: boolean | null;
  min?: number | null;
  max?: number | null;
  step?: number | null;
  units?: string | null;
  options?: string[] | null;
  section?: string | null;
  visible_when?: string | null;
  visible_when_value?: unknown;
}

export interface NodeInputs {
  required: WidgetSpec[];
  optional: WidgetSpec[];
  hidden: WidgetSpec[];
}

export interface NodeOutput { name: string; type: string; }

export interface NodeContract {
  id: string;
  title: string;
  category: string;
  description?: string | null;
  inputs: NodeInputs;
  outputs: NodeOutput[];
  min_size?: [number, number] | null;
  family?: string | null;
}

export const SETTINGS_PREFIX = "FiL_Design_ImageMind.";

export const NODE_CONTRACTS: Record<string, NodeContract> = {
  "FiLSeed": {
  "id": "FiLSeed",
  "title": "♻️ Seed",
  "category": "🎨 FiL Design/Values",
  "description": "Fixed or randomized seed with copy and reuse buttons.",
  "inputs": {
    "required": [
      {
        "name": "mode",
        "kind": "segmented",
        "label": "Mode",
        "default": "random",
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": [
          "random",
          "fixed"
        ],
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "seed",
        "kind": "number",
        "label": "Seed",
        "default": 0,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 999999999999,
        "step": 1,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      }
    ],
    "optional": [
      {
        "name": "copy_to_clipboard",
        "kind": "boolean",
        "label": "Copy seed",
        "default": false,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "actions",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "use_last_seed",
        "kind": "boolean",
        "label": "Use last seed",
        "default": false,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "actions",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "new_fixed",
        "kind": "boolean",
        "label": "New fixed random",
        "default": false,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "actions",
        "visible_when": null,
        "visible_when_value": null
      }
    ],
    "hidden": []
  },
  "outputs": [
    {
      "name": "seed",
      "type": "INT"
    }
  ],
  "min_size": [
    220,
    180
  ],
  "family": "value"
},
  "FiLProviderLoader": {
  "id": "FiLProviderLoader",
  "title": "🔌 Provider Loader",
  "category": "🎨 FiL Design/LLM",
  "description": "Provider and model runtime configuration.",
  "inputs": {
    "required": [
      {
        "name": "provider",
        "kind": "combo",
        "label": "Provider",
        "default": "ollama",
        "tooltip": null,
        "values": [
          "ollama",
          "lmstudio",
          "openai",
          "google",
          "groq",
          "openrouter",
          "cloudflare"
        ],
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "model",
        "kind": "combo",
        "label": "Model",
        "default": "(loading...)",
        "tooltip": null,
        "values": [
          "(loading...)"
        ],
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "refresh_models",
        "kind": "boolean",
        "label": "Refresh models",
        "default": false,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "actions",
        "visible_when": null,
        "visible_when_value": null
      }
    ],
    "optional": [
      {
        "name": "temperature",
        "kind": "slider",
        "label": "Temperature",
        "default": 0.7,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 2,
        "step": 0.05,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "max_tokens",
        "kind": "number",
        "label": "Max tokens",
        "default": 0,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 65536,
        "step": 1,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "rate_limit_ms",
        "kind": "number",
        "label": "Rate limit (ms)",
        "default": 100,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 5000,
        "step": 10,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "seed",
        "kind": "number",
        "label": "Seed",
        "default": -1,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": -1,
        "max": 999999999999,
        "step": 1,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "max_image_side",
        "kind": "number",
        "label": "Max image side",
        "default": 1024,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 128,
        "max": 4096,
        "step": 64,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      }
    ],
    "hidden": []
  },
  "outputs": [
    {
      "name": "config",
      "type": "DICT"
    },
    {
      "name": "model",
      "type": "STRING"
    }
  ],
  "min_size": [
    300,
    320
  ],
  "family": "llm"
},
  "FiLOpticScanner": {
  "id": "FiLOpticScanner",
  "title": "🕵️ Optic Scanner",
  "category": "🎨 FiL Design/LLM",
  "description": "Image analysis or text-idea expansion into a generation prompt.",
  "inputs": {
    "required": [
      {
        "name": "prompt",
        "kind": "string",
        "label": null,
        "default": "",
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "prompt",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "negative_prompt",
        "kind": "string",
        "label": null,
        "default": "",
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "prompt",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "custom_style",
        "kind": "string",
        "label": null,
        "default": "",
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "prompt",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "response_format",
        "kind": "segmented",
        "label": null,
        "default": "text",
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": [
          "text",
          "json"
        ],
        "section": "prompt",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "agent",
        "kind": "chip_grid",
        "label": null,
        "default": "Universal",
        "tooltip": null,
        "values": [
          "None",
          "Universal",
          "Portrait",
          "Products",
          "Nature & Landscape",
          "Art & Illustration",
          "Ultra Detailed Expert",
          "Cinematic Master",
          "18+",
          "Fashion",
          "Animals",
          "Character Performance Agent",
          "Architecture",
          "Interior",
          "City",
          "Transport",
          "Food",
          "Gadgets",
          "Games",
          "Composition Agent",
          "Lighting & Color Agent",
          "Professional Tagger"
        ],
        "columns": 3,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "agent",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "model_type",
        "kind": "chip_grid",
        "label": null,
        "default": "Auto/None",
        "tooltip": null,
        "values": [
          "Auto/None",
          "Z-Image Turbo",
          "FLUX",
          "SDXL",
          "QWEN",
          "Krea 2",
          "Ideogram 4"
        ],
        "columns": 3,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "model",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "detail_level",
        "kind": "chip_grid",
        "label": null,
        "default": "normal",
        "tooltip": null,
        "values": [
          "tiny",
          "short",
          "normal",
          "detailed",
          "ultra"
        ],
        "columns": 5,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "output",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "language",
        "kind": "combo",
        "label": null,
        "default": "en",
        "tooltip": null,
        "values": [
          "en",
          "ru"
        ],
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "output",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "prompt_mode",
        "kind": "segmented",
        "label": null,
        "default": "Auto",
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": [
          "Auto",
          "Hybrid",
          "Two-Stage"
        ],
        "section": "output",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "photo_style",
        "kind": "chip_list",
        "label": null,
        "default": "None",
        "tooltip": null,
        "values": [
          "None",
          "📷 КАМЕРЫ/📷 Disposable 90s",
          "📷 КАМЕРЫ/📸 Polaroid 600",
          "📷 КАМЕРЫ/📷 Hasselblad 70mm",
          "📷 КАМЕРЫ/🕳️ Pinhole Obscura",
          "📷 КАМЕРЫ/📹 CCTV surveillance",
          "📷 КАМЕРЫ/🚓 Police Dashcam",
          "📷 КАМЕРЫ/🎞️ Raw 35mm Photo",
          "📐 МОДИФИКАТОРЫ/🛩️ Drone Photo",
          "📐 МОДИФИКАТОРЫ/🔭 Ultra Wide 12mm",
          "📐 МОДИФИКАТОРЫ/🌐 Fisheye Lens",
          "📐 МОДИФИКАТОРЫ/📐 Dutch Angle",
          "📐 МОДИФИКАТОРЫ/📹 GoPro POV Action",
          "🎬 КИНО/🎞️ IMAX Production",
          "🎬 КИНО/🌑 Film Noir",
          "🎬 КИНО/🌈 Technicolor 50s",
          "🎬 КИНО/📷 Anamorphic Wide",
          "🎬 КИНО/🎬 Gangster Cinema",
          "⏱️ ЗАХВАТ/💫 Motion Blur",
          "⏱️ ЗАХВАТ/📸 Action Freeze",
          "⏱️ ЗАХВАТ/🎞️ Slo-Mo Bullet Time",
          "🕰️ РЕТРО/🎞️ Vintage 70s Portra",
          "🕰️ РЕТРО/🪞 Daguerreotype",
          "🕰️ РЕТРО/🧪 Wet Plate Collodion",
          "🕰️ РЕТРО/🟤 Sepia Nostalgia",
          "🕰️ РЕТРО/🎸 Rockabilly 50s",
          "🕰️ РЕТРО/🎩 Gilded Gangster",
          "🕰️ РЕТРО/🎬 Nostalgic 8mm",
          "🏠 ИНТЕРЬЕР/🏭 Loft Industrial",
          "🏠 ИНТЕРЬЕР/🌻 Provence Rustic",
          "🏠 ИНТЕРЬЕР/🕉️ Boho Chic",
          "🏠 ИНТЕРЬЕР/🌿 Eco-Style Design",
          "🏠 ИНТЕРЬЕР/👑 Baroque Ornate",
          "🏠 ИНТЕРЬЕР/⬜ Minimalism",
          "🏠 ИНТЕРЬЕР/🏡 Country House",
          "👗 ФЭШН/📸 Editorial Vogue",
          "👗 ФЭШН/👤 Portrait Bokeh",
          "👗 ФЭШН/✨ Glamour Glow",
          "👗 ФЭШН/🖤 Chanel Aesthetic",
          "👗 ФЭШН/💋 Pin-up Style",
          "👗 ФЭШН/👔 Business Pro",
          "👗 ФЭШН/👠 Fashion Runway",
          "👗 ФЭШН/🛍️ Street Fashion",
          "🏙️ СРЕДА/🌃 Cyberpunk Neon",
          "🏙️ СРЕДА/🌧️ Rainy Neon Noir",
          "🏙️ СРЕДА/🌫️ Foggy Neon Noir",
          "🏙️ СРЕДА/🏚️ Dystopian Megacity",
          "🏙️ СРЕДА/🧱 Urban Grunge",
          "🏙️ СРЕДА/📷 Street Candid",
          "🏙️ СРЕДА/🌅 Magic Hour",
          "🏙️ СРЕДА/☔ Rain Monsoon Puddle",
          "🏙️ СРЕДА/🇬🇧 London Smog",
          "🏜️ ЖАНРЫ/🏔️ Пейзажный Landscape",
          "🏜️ ЖАНРЫ/🦁 Nat Geo Scale",
          "🏜️ ЖАНРЫ/🔬 Macro Micro-world",
          "🏜️ ЖАНРЫ/🌌 Astro Cosmic",
          "🏜️ ЖАНРЫ/✈️ Travel Adventure",
          "🏜️ ЖАНРЫ/🪶 Ethnic Spirit",
          "🏜️ ЖАНРЫ/🏜️ Saharan Mirage",
          "📸 РЕПОРТАЖ/☕ Lifestyle Moment",
          "📸 РЕПОРТАЖ/📋 Documentary Truth",
          "📸 РЕПОРТАЖ/💼 Stock Quality",
          "🧪 ЭФФЕКТЫ/🤖 Holographic HUD",
          "🧪 ЭФФЕКТЫ/💡 Hard Rim Neon",
          "🧪 ЭФФЕКТЫ/🎨 Chromatic Aberration",
          "🧪 ЭФФЕКТЫ/💎 Prism Optical Fracture",
          "🧪 ЭФФЕКТЫ/🌫️ Volumetric Tyndall Dust",
          "🧪 ЭФФЕКТЫ/📼 Expired Chemical Leak",
          "🧪 ЭФФЕКТЫ/☀️ High-Key Airy",
          "🧪 ЭФФЕКТЫ/🌈 HDR Dynamic",
          "🧪 ЭФФЕКТЫ/🕯️ Candlelit Mood",
          "🧪 ЭФФЕКТЫ/🔴 Infrared Surreal",
          "🦾 КИБЕРПАНК/📱 Sleek White Android",
          "🦾 КИБЕРПАНК/🪞 Chrome Android",
          "🦾 КИБЕРПАНК/💉 Wirehead Junkie",
          "🦾 КИБЕРПАНК/🏢 Corpo-Cyborg",
          "🦾 КИБЕРПАНК/🎖️ Military Cyborg",
          "🦾 КИБЕРПАНК/⚔️ Cyber-Samurai",
          "🦾 КИБЕРПАНК/🧬 Biomechanical Giger",
          "🦾 КИБЕРПАНК/🧪 Biopunk Organic",
          "🦾 КИБЕРПАНК/🌱 Solarpunk Hybrid",
          "🦾 КИБЕРПАНК/💀 Post-Apoc Cyber",
          "🦾 КИБЕРПАНК/🌃 Neon Cyberpunk City Rain",
          "🦾 КИБЕРПАНК/🚗 JDM Neon Street Racer",
          "🦾 КИБЕРПАНК/🌇 Electric Sunset Megacity",
          "🦾 КИБЕРПАНК/🛰️ Holographic Interface Portrait",
          "🦾 КИБЕРПАНК/🗡️ Dark Samurai Street",
          "🦾 КИБЕРПАНК/🤖 Chrome Cyborg Hyperrealism",
          "🦾 КИБЕРПАНК/🦾 Cybernetic Arm Close-Up",
          "🦾 КИБЕРПАНК/🧠 Biomechanical Horror Realism",
          "🦾 КИБЕРПАНК/🕶️ Teal Gold Cyber Noir Portrait",
          "🦾 КИБЕРПАНК/🧬 Synthetic Skin Android Portrait",
          "🦾 КИБЕРПАНК/🤍 White Android Minimal Studio",
          "🦾 КИБЕРПАНК/🏭 Industrial Cyborg Portrait",
          "🦾 КИБЕРПАНК/🫀 Bio-Mechanical Core",
          "🦾 КИБЕРПАНК/🧩 Android Anatomy Cutaway",
          "🦾 КИБЕРПАНК/🧡 Golden Mechanical Luxury",
          "🦾 КИБЕРПАНК/🪦 Melancholic Robot Portrait",
          "🦾 КИБЕРПАНК/🩻 X-Ray Cyber Radiograph",
          "🦾 КИБЕРПАНК/💎 Prismatic Neon Reflections",
          "🦾 КИБЕРПАНК/🪞 Molten Liquid Chrome Realism",
          "🦾 КИБЕРПАНК/🌫️ Atmospheric Sci-Fi Mist",
          "🧪 ЭФФЕКТЫ/📡 Тесла-катушка",
          "🧪 ЭФФЕКТЫ/🪞 Зеркальный мир",
          "🧪 ЭФФЕКТЫ/📺 CRT Scanlines",
          "🧪 ЭФФЕКТЫ/🔦 Полицейский прожектор",
          "🧪 ЭФФЕКТЫ/🌊 Цифровой муар",
          "🧪 ЭФФЕКТЫ/🫧 Мыльные пузыри",
          "🧪 ЭФФЕКТЫ/🕶️ Солнечное затмение",
          "🧪 ЭФФЕКТЫ/📠 Факс-аппарат",
          "🧪 ЭФФЕКТЫ/🟣 UV Fluorescence",
          "🧪 ЭФФЕКТЫ/💥 High-Speed Shatter",
          "🧪 ЭФФЕКТЫ/🎨 Light Painting",
          "🧪 ЭФФЕКТЫ/👯 Double Exposure",
          "🧪 ЭФФЕКТЫ/🌑 Silhouette Drama",
          "🧪 ЭФФЕКТЫ/🧊 Absolute Zero",
          "🧪 ЭФФЕКТЫ/⚒️ Forgemaster Heat",
          "🧪 ЭФФЕКТЫ/🌡️ Thermal Imager",
          "🧪 ЭФФЕКТЫ/☢️ X-Ray Radiograph",
          "🧪 ЭФФЕКТЫ/🌊 Bioluminescence",
          "🧪 ЭФФЕКТЫ/🎭 Hard Chiaroscuro",
          "🧪 ЭФФЕКТЫ/🔬 Electron Micro",
          "🗺️ СЦЕНЫ/🎪 Circus Big Top",
          "🗺️ СЦЕНЫ/🛁 Bathroom Mirror",
          "🗺️ СЦЕНЫ/🔮 Crystal Ball",
          "🗺️ СЦЕНЫ/🖼️ Art Gallery",
          "🗺️ СЦЕНЫ/🛒 Grocery Store",
          "🗺️ СЦЕНЫ/🛩️ Airplane Window",
          "🗺️ СЦЕНЫ/🎢 Amusement Park",
          "🗺️ СЦЕНЫ/🌊 Ocean Wave",
          "🗺️ СЦЕНЫ/🏊 Swimming Pool",
          "🗺️ СЦЕНЫ/🏜️ Desert Road",
          "🗺️ СЦЕНЫ/🍄 Fairy Forest",
          "🗺️ СЦЕНЫ/🗿 Ancient Ruins",
          "🗺️ СЦЕНЫ/🎹 Piano Studio",
          "🗺️ СЦЕНЫ/🧖 Spa Towel",
          "🗺️ СЦЕНЫ/📚 Library Shelf",
          "🗺️ СЦЕНЫ/🪜 Construction Site",
          "🗺️ СЦЕНЫ/🏚️ Abandoned Building",
          "🗺️ СЦЕНЫ/🖤 Black Light Party",
          "🗺️ СЦЕНЫ/🏮 Lantern Festival",
          "🗺️ СЦЕНЫ/🔦 Flashlight Beam",
          "🗺️ СЦЕНЫ/🏺 Pottery Studio",
          "🗺️ СЦЕНЫ/🕯️ Candle Meditation",
          "🗺️ СЦЕНЫ/🪴 Plant Nursery",
          "🗺️ СЦЕНЫ/🎤 Recording Studio",
          "🗺️ СЦЕНЫ/🧸 Cozy Bedroom",
          "🗺️ СЦЕНЫ/🏗️ Skyscraper Edge",
          "🗺️ СЦЕНЫ/🍳 Kitchen Morning",
          "🗺️ СЦЕНЫ/⛺ Campfire Night",
          "🗺️ СЦЕНЫ/🧗 Rock Climbing",
          "🗺️ СЦЕНЫ/🛒 Vintage Store",
          "🗺️ СЦЕНЫ/🌉 Golden Gate",
          "🗺️ СЦЕНЫ/🛁 Rainy Window",
          "🗺️ СЦЕНЫ/🪐 Neon Desert",
          "🗺️ СЦЕНЫ/🥾 Hiking Trail",
          "🗺️ СЦЕНЫ/🌾 Rice Terraces",
          "🗺️ СЦЕНЫ/🛀 Floating Bath"
        ],
        "columns": null,
        "searchable": true,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "styles",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "nsfw_photo_style",
        "kind": "chip_list",
        "label": null,
        "default": "None",
        "tooltip": null,
        "values": [
          "None",
          "📸 СТУДИЯ/📸 Studio Elite",
          "📸 СТУДИЯ/✨ Glamour Core",
          "📸 СТУДИЯ/🛋️ Boudoir",
          "📸 СТУДИЯ/🌅 Morning Boudoir",
          "📸 СТУДИЯ/👙 Fashion Lingerie",
          "🏠 ИНТЕРЬЕР/🛏️ Bedroom Intimate",
          "🏠 ИНТЕРЬЕР/🚿 Shower Scene",
          "🏠 ИНТЕРЬЕР/🛁 Bath Scene",
          "🏠 ИНТЕРЬЕР/🪞 Vanity Mirror",
          "🏠 ИНТЕРЬЕР/🛋️ Living Room",
          "🌿 ПРИРОДА/🌊 Beach Sunset",
          "🌿 ПРИРОДА/🌲 Forest Glade",
          "🌿 ПРИРОДА/🌸 Garden Path",
          "🌿 ПРИРОДА/⛺ Private Pool",
          "🎭 ФЭШН/💋 Beauty Close-up",
          "🎭 ФЭШН/📸 Fashion Editorial",
          "🎭 ФЭШН/👗 Dressed to Kill",
          "🎭 ФЭШН/🩱 Swimsuit Campaign",
          "🌑 НУАР/⛓️ Fetish Noir",
          "🌑 НУАР/🛏️ Bedroom",
          "🌑 НУАР/🎭 Venetian Velvet",
          "🌑 НУАР/🔦 Interrogation Room",
          "🌑 НУАР/🎪 Carnival",
          "🌑 НУАР/⚰️ Gothic Romance",
          "🌑 НУАР/🧛 Vampire Gothic",
          "🌑 НУАР/🌑 Intimate Shadows",
          "🛀 ТЕКСТУРЫ/💦 Wet Skin",
          "🛀 ТЕКСТУРЫ/🫒 Wet & Glossy",
          "🛀 ТЕКСТУРЫ/🛁 Steamy Bathtub",
          "🛀 ТЕКСТУРЫ/🥛 Milk Bath Editorial",
          "🛀 ТЕКСТУРЫ/🚿 Frosted Glass Shower",
          "🛀 ТЕКСТУРЫ/🌊 Underwater Weightless",
          "🛀 ТЕКСТУРЫ/🎨 Nude Aesthetic",
          "🛀 ТЕКСТУРЫ/👘 Silk & Lace",
          "🛀 ТЕКСТУРЫ/🕸️ Spiderweb Silk",
          "🏙️ ЛОКАЦИИ/🤳 Amateur POV",
          "🏙️ ЛОКАЦИИ/📹 Amateur Real",
          "🏙️ ЛОКАЦИИ/🪩 Nightclub Dark",
          "🏙️ ЛОКАЦИИ/🏖️ Beach Sensual",
          "🏙️ ЛОКАЦИИ/☔ Neon Rain Cyberpunk",
          "🏙️ ЛОКАЦИИ/🚗 Backseat Tryst",
          "🏙️ ЛОКАЦИИ/🏨 Hotel Room Neon",
          "🏙️ ЛОКАЦИИ/❄️ Winter Cabin",
          "🏙️ ЛОКАЦИИ/🏜️ Desert Oasis",
          "🏙️ ЛОКАЦИИ/🏙️ Skyscraper Penthouse",
          "🏙️ ЛОКАЦИИ/🔧 Garage Oil & Chrome",
          "🦾 КИБЕРПАНК/🌃 Neon Alley Exposure",
          "🦾 КИБЕРПАНК/🤖 Chrome Implant Nude",
          "🦾 КИБЕРПАНК/🧬 Synthetic Skin Android Nude",
          "🦾 КИБЕРПАНК/🪩 Holographic Strip Club",
          "🦾 КИБЕРПАНК/🩺 Ripperdoc Aftercare",
          "🦾 КИБЕРПАНК/⛓️ Cyber Latex Dungeon",
          "🦾 КИБЕРПАНК/🌧️ Rain-Slick Rooftop Nude",
          "🦾 КИБЕРПАНК/📹 Backroom Neon POV",
          "🦾 КИБЕРПАНК/🚦 Red-Light District Android",
          "🦾 КИБЕРПАНК/🪞 Augmented Mirror Selfie",
          "🦾 КИБЕРПАНК/💡 Bioluminescent Body Ports",
          "🦾 КИБЕРПАНК/🏙️ Drone-Lit Penthouse Nude",
          "🦾 КИБЕРПАНК/🚿 Wet Chrome Shower Pod",
          "🦾 КИБЕРПАНК/🎤 Virtual Idol Dressing Room",
          "🦾 КИБЕРПАНК/🩻 Holo-Tattoo Nude Scan",
          "🦾 КИБЕРПАНК/🫧 Glass Capsule Display",
          "🦾 КИБЕРПАНК/🏍️ Neon Motorcycle Garage",
          "🦾 КИБЕРПАНК/🟣 Blacklight Cyber Boudoir",
          "🦾 КИБЕРПАНК/🖥️ Server Room Heat",
          "🦾 КИБЕРПАНК/💎 Prismatic Implant Glamour"
        ],
        "columns": null,
        "searchable": true,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "styles",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "art_style",
        "kind": "chip_list",
        "label": null,
        "default": "None",
        "tooltip": null,
        "values": [
          "None",
          "🎨 ЖИВОПИСЬ/🖌️ Impasto Oil",
          "🎨 ЖИВОПИСЬ/💧 Wet Watercolor",
          "🎨 ЖИВОПИСЬ/🔪 Palette Knife",
          "🎨 ЖИВОПИСЬ/🌸 Ghibli Inspired",
          "🎨 ЖИВОПИСЬ/🗿 Classical Marble",
          "🎨 ЖИВОПИСЬ/🎭 Baroque Drama",
          "🎨 ЖИВОПИСЬ/🖼️ Renaissance",
          "🎨 ЖИВОПИСЬ/🎪 Impressionist",
          "🎨 ЖИВОПИСЬ/🖌️ Asian Ink",
          "🎨 ЖИВОПИСЬ/🖌️ Sumi-e",
          "✏️ ГРАФИКА/✏️ Pencil Sketch",
          "✏️ ГРАФИКА/🖊️ Ink Illustration",
          "✏️ ГРАФИКА/🖍️ Charcoal Drawing",
          "✏️ ГРАФИКА/✏️ Graphite Study",
          "✏️ ГРАФИКА/🖋️ Pen & Ink",
          "💻 ЦИФРОВАЯ/👾 Pixel Art",
          "💻 ЦИФРОВАЯ/📐 Vector Art",
          "💻 ЦИФРОВАЯ/🎨 Digital Painting",
          "💻 ЦИФРОВАЯ/🤖 AI Art Style",
          "💻 ЦИФРОВАЯ/🌆 Concept Art",
          "💻 ЦИФРОВАЯ/🏮 Anime Style",
          "💻 ЦИФРОВАЯ/🗾 Manga Style",
          "💻 ЦИФРОВАЯ/🎮 Game UI",
          "💻 ЦИФРОВАЯ/🎲 Tabletop RPG",
          "🏛️ ИСТОРИЯ/🏺 Ancient Egyptian",
          "🏛️ ИСТОРИЯ/🏛️ Greek Classical",
          "🏛️ ИСТОРИЯ/🗿 Roman Bust",
          "🏛️ ИСТОРИЯ/🖼️ Medieval Icon",
          "🏛️ ИСТОРИЯ/⚔️ Viking Art",
          "🏛️ ИСТОРИЯ/🏰 Art Nouveau",
          "🏛️ ИСТОРИЯ/🎭 Art Deco",
          "🔬 СТИЛИЗАЦИЯ/🔍 Hyperrealism",
          "🔬 СТИЛИЗАЦИЯ/🌫️ Vaporwave",
          "🔬 СТИЛИЗАЦИЯ/🎲 Glitch Art",
          "🔬 СТИЛИЗАЦИЯ/💎 Steampunk",
          "🔬 СТИЛИЗАЦИЯ/🌸 Kawaii",
          "🔬 СТИЛИЗАЦИЯ/🦋 Morbid",
          "🔬 СТИЛИЗАЦИЯ/🔮 Mystical",
          "🔬 СТИЛИЗАЦИЯ/🎪 Circus Noir",
          "💥 КОМИКС/🎬 Dynamic Cel-Shaded",
          "💥 КОМИКС/🎌 Manga Screen-tone",
          "💥 КОМИКС/💥 Action Comic",
          "💥 КОМИКС/📜 Comic Cover",
          "💥 КОМИКС/🤖 Киберпанк-комикс",
          "💥 КОМИКС/💡 Неон-комикс",
          "💥 КОМИКС/💋 Пин-ап комикс",
          "💥 КОМИКС/📼 Ретро-комикс",
          "💥 КОМИКС/⚙️ Стимпанк-комикс",
          "💥 КОМИКС/⚰️ Готический комикс",
          "💥 КОМИКС/👑 Барокко-комикс",
          "💥 КОМИКС/⚫ Блэк-энд-уайт",
          "🦾 КИБЕРПАНК/🎮 Mecha Pilot",
          "🦾 КИБЕРПАНК/⚛️ Nanopunk Swarm",
          "🦾 КИБЕРПАНК/💉 Neon Tattoos",
          "🦾 КИБЕРПАНК/🤖 Flesh-to-Steel Fusion",
          "🦾 КИБЕРПАНК/💊 Neuro-Interface",
          "🦾 КИБЕРПАНК/🩸 Bio-Corroded Tech",
          "👾 ДИДЖИТАЛ/🏄 Vaporwave Cyber",
          "👾 ДИДЖИТАЛ/👓 Anaglyph Red-Blue",
          "👾 ДИДЖИТАЛ/🔆 Octane Render",
          "👾 ДИДЖИТАЛ/🌅 Synthwave Art",
          "👾 ДИДЖИТАЛ/💧 Molten Liquid Chrome",
          "👾 ДИДЖИТАЛ/🖥️ Holographic UI",
          "👾 ДИДЖИТАЛ/📺 Киберпоп",
          "👾 ДИДЖИТАЛ/🎨 Коллаж-арт",
          "👾 ДИДЖИТАЛ/🔀 Сегментация-арт",
          "👾 ДИДЖИТАЛ/🎭 Постер-арт",
          "👾 ДИДЖИТАЛ/🚗 Лоурайдер-арт",
          "💻 ЦИФРОВАЯ/🌃 Neon Cyberpunk City Rain",
          "💻 ЦИФРОВАЯ/🚗 Retro Anime JDM Car Wallpaper",
          "💻 ЦИФРОВАЯ/🏍️ Anime Motorcycle Action Poster",
          "💻 ЦИФРОВАЯ/🌇 Electric Sunset Sci-Fi Landscape",
          "💻 ЦИФРОВАЯ/🔮 Crystal Overload Sci-Fi",
          "💻 ЦИФРОВАЯ/🧊 Cold Blue Anime Macro",
          "💻 ЦИФРОВАЯ/🌊 Soft Water Reflection Anime",
          "💻 ЦИФРОВАЯ/🌌 Lofi Anime City Melancholy",
          "💻 ЦИФРОВАЯ/📼 Retro 90s Anime Cel",
          "💻 ЦИФРОВАЯ/🎀 Cute Pink Anime Portrait",
          "💻 ЦИФРОВАЯ/🐉 Fantasy Dragon Girl Anime",
          "💻 ЦИФРОВАЯ/🚘 Night Street Car Cinematic",
          "💻 ЦИФРОВАЯ/🪄 Sorceress Neon Ritual Anime",
          "💻 ЦИФРОВАЯ/🎧 Moody Headphone Anime Girl",
          "💻 ЦИФРОВАЯ/🏁 Street Racing Anime Poster",
          "💻 ЦИФРОВАЯ/🍭 Soft Pastel Kawaii Car",
          "💻 ЦИФРОВАЯ/🏙️ Urban Fashion Editorial Anime",
          "💻 ЦИФРОВАЯ/🌫️ Atmospheric Sci-Fi Mist",
          "💻 ЦИФРОВАЯ/🌆 Neo-Tokyo Anime Adventure",
          "💻 ЦИФРОВАЯ/📱 Phone Wallpaper Vertical Sci-Fi",
          "💻 ЦИФРОВАЯ/🎮 Anime Game Character Render",
          "💻 ЦИФРОВАЯ/🧜 Ethereal Soft Fantasy Anime",
          "💻 ЦИФРОВАЯ/🗡️ Dark Samurai Cyber Anime",
          "💻 ЦИФРОВАЯ/🛰️ Holographic Interface Portrait",
          "💻 ЦИФРОВАЯ/🧩 Abstract Cyber Shape Design",
          "💻 ЦИФРОВАЯ/🚨 Warning Sign AI Robot Art",
          "💻 ЦИФРОВАЯ/🖼️ Pinterest Vertical AI Art Mix",
          "🔬 СТИЛИЗАЦИЯ/🖤 Dark Anime Witch Gothic",
          "🔬 СТИЛИЗАЦИЯ/🩸 Vampire Red Eye Anime Noir",
          "🔬 СТИЛИЗАЦИЯ/🎭 Hyperpop Character Illustration",
          "🔬 СТИЛИЗАЦИЯ/🦇 Gothic Dark Fantasy Portrait",
          "🔬 СТИЛИЗАЦИЯ/🌹 Dark Floral Gothic Editorial",
          "🔬 СТИЛИЗАЦИЯ/🫧 Iridescent Hologram Fashion",
          "🔬 СТИЛИЗАЦИЯ/🧛 Crimson Gothic Beauty",
          "🔬 СТИЛИЗАЦИЯ/🌠 Cosmic Dream Girl",
          "🔬 СТИЛИЗАЦИЯ/💿 Holographic Y2K Pop Star",
          "🔬 СТИЛИЗАЦИЯ/🛸 Alien Fashion Runway",
          "🔬 СТИЛИЗАЦИЯ/🏴 Black Armor Dark Fantasy",
          "🔬 СТИЛИЗАЦИЯ/🕯️ Occult Black Magic Anime",
          "🔬 СТИЛИЗАЦИЯ/🕳️ Black Void High Contrast",
          "🔬 СТИЛИЗАЦИЯ/🧱 Gritty Post-Apocalyptic Casual",
          "🔬 СТИЛИЗАЦИЯ/🔥 Red Smoke Dark Character",
          "🔬 СТИЛИЗАЦИЯ/💎 Prismatic Neon Reflections",
          "🔬 СТИЛИЗАЦИЯ/🪞 Glossy Black Latex Cyber",
          "🔬 СТИЛИЗАЦИЯ/🌸 Bloom Soft Girl Aesthetic",
          "💥 КОМИКС/🕷️ Symbiote Venom Comic Ink",
          "💥 КОМИКС/⚡ Aggressive Comic Ink Splash",
          "💥 КОМИКС/🧨 Dynamic Superhero Splash",
          "🦾 КИБЕРПАНК/🤖 Chrome Cyborg Hyperrealism",
          "🦾 КИБЕРПАНК/🦾 Cybernetic Arm Concept Art",
          "🦾 КИБЕРПАНК/🧠 Biomechanical Body Horror",
          "🦾 КИБЕРПАНК/🕶️ Teal Gold Cyberpunk Noir Portrait",
          "🦾 КИБЕРПАНК/🧬 Synthetic Skin Android Portrait",
          "🦾 КИБЕРПАНК/🦾 White Android Minimal Portrait",
          "🦾 КИБЕРПАНК/🩶 Industrial Female Cyborg Portrait",
          "🦾 КИБЕРПАНК/🫀Bio-Mechanical Core Portrait",
          "🦾 КИБЕРПАНК/🧬 Android Anatomy Cutaway",
          "🦾 КИБЕРПАНК/🦋 Angelic Cyber Feminine",
          "🦾 КИБЕРПАНК/🧡 Golden Mechanical Portrait",
          "🦾 КИБЕРПАНК/🪦 Melancholic Robot Portrait",
          "🦾 КИБЕРПАНК/🩻 X-Ray Skeleton Cyber Anime"
        ],
        "columns": null,
        "searchable": true,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "styles",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "nsfw_art_style",
        "kind": "chip_list",
        "label": null,
        "default": "None",
        "tooltip": null,
        "values": [
          "None",
          "🎨 ИЛЛЮСТРАЦИЯ/🖌️ Pro Hentai",
          "🎨 ИЛЛЮСТРАЦИЯ/💎 Premium Hentai",
          "🎨 ИЛЛЮСТРАЦИЯ/🌸 Anime Ecchi",
          "🎨 ИЛЛЮСТРАЦИЯ/🦸 Western Adult",
          "🎨 ИЛЛЮСТРАЦИЯ/🎯 Digital Pin-up",
          "💻 ЦИФРОВАЯ/🧊 3D Render",
          "💻 ЦИФРОВАЯ/🖥️ CGI",
          "💻 ЦИФРОВАЯ/🤖 AI Generated",
          "📜 КЛАССИКА/🖼️ Baroque Nude",
          "📜 КЛАССИКА/🏛️ Academic Nude",
          "📜 КЛАССИКА/🎭 Impressionist Nude",
          "🎯 ЖАНРЫ/🔞 Explicit",
          "🎯 ЖАНРЫ/🎭 Sensual Art",
          "🎯 ЖАНРЫ/📸 Fetish Art",
          "🎨 ИЛЛЮСТРАЦИЯ/🎭 Kabuki Demon",
          "🎨 ИЛЛЮСТРАЦИЯ/🌺 Tropical Adult",
          "🎨 ИЛЛЮСТРАЦИЯ/🌿 Botanical Nymph",
          "🖌️ ЖИВОПИСЬ/👼 Renaissance Oil",
          "🖌️ ЖИВОПИСЬ/🔪 Thick Impasto",
          "🖌️ ЖИВОПИСЬ/💧 Watercolor Soft",
          "🖌️ ЖИВОПИСЬ/🎨 Artistic Nude",
          "🖌️ ЖИВОПИСЬ/🛢️ Oil Painting",
          "✒️ СКЕТЧ/✒️ Ink Erotica",
          "✒️ СКЕТЧ/🦴 Raw Anatomy",
          "✒️ СКЕТЧ/💀 Macabre Ink",
          "🏰 ФЭНТЕЗИ/🧝 Dark Fantasy",
          "🏰 ФЭНТЕЗИ/🧝 Dark Desire",
          "🏰 ФЭНТЕЗИ/🏛️ Mythological Nude",
          "🏰 ФЭНТЕЗИ/🌊 Aquatic Erotic",
          "🏰 ФЭНТЕЗИ/🏜️ Dune Fantasy",
          "🏰 ФЭНТЕЗИ/🧚 Fairy Tale",
          "🏰 ФЭНТЕЗИ/🎨 NSFW Art",
          "🚀 SCI-FI/🛸 Sci-Fi Adult",
          "🚀 SCI-FI/🤖 Cyberpunk NSFW",
          "🚀 SCI-FI/🦾 Mecha-Musume",
          "🚀 SCI-FI/💎 Crystal Anatomy",
          "🚀 SCI-FI/🌋 Lava Forged",
          "🦾 КИБЕРПАНК/👽 Synthetic Skin",
          "🦾 КИБЕРПАНК/👘 Cyber-Geisha",
          "🦾 КИБЕРПАНК/⛓️ Chrome Bondage",
          "🦾 КИБЕРПАНК/🧩 Fragmented Body",
          "🦾 КИБЕРПАНК/💡 Glowing Fiber Optics",
          "🕰️ РЕТРО/🎭 Retro Cabaret",
          "🕰️ РЕТРО/🌿 Nouveau Adult",
          "🕰️ РЕТРО/🌸 Shoujo Romance",
          "🕰️ РЕТРО/📼 80s Anime OVA"
        ],
        "columns": null,
        "searchable": true,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "styles",
        "visible_when": null,
        "visible_when_value": null
      }
    ],
    "optional": [],
    "hidden": []
  },
  "outputs": [
    {
      "name": "prompt",
      "type": "STRING"
    },
    {
      "name": "metadata_json",
      "type": "STRING"
    },
    {
      "name": "metadata_dict",
      "type": "DICT"
    }
  ],
  "min_size": [
    400,
    600
  ],
  "family": "llm"
},
  "FiLNeuroCleaner": {
  "id": "FiLNeuroCleaner",
  "title": "🧹 Cleaner",
  "category": "🎨 FiL Design/Tools",
  "description": "GPU VRAM and loaded model memory cleanup.",
  "inputs": {
    "required": [
      {
        "name": "clean_vram",
        "kind": "boolean",
        "label": "Flush GPU Cache",
        "default": true,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "unload_diffusion",
        "kind": "boolean",
        "label": "Unload Diffusion (FLUX/SD)",
        "default": true,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "unload_clip",
        "kind": "boolean",
        "label": "Unload CLIP / Text Encoder",
        "default": false,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "unload_vae",
        "kind": "boolean",
        "label": "Unload VAE",
        "default": false,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "unload_control",
        "kind": "boolean",
        "label": "Unload ControlNet / Adapter",
        "default": false,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      }
    ],
    "optional": [],
    "hidden": []
  },
  "outputs": [
    {
      "name": "output",
      "type": "ANY"
    }
  ],
  "min_size": [
    280,
    200
  ],
  "family": "tool"
},
  "FiLBeforeAfterCompare": {
  "id": "FiLBeforeAfterCompare",
  "title": "🔄 Compare",
  "category": "🎨 FiL Design/Image",
  "description": "Before/after preview with optional output resizing.",
  "inputs": {
    "required": [],
    "optional": [
      {
        "name": "swap",
        "kind": "segmented",
        "label": "Swap before/after",
        "default": "OFF",
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": [
          "ON",
          "OFF"
        ],
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "resize_mode",
        "kind": "segmented",
        "label": "Resize mode",
        "default": "Off",
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": [
          "Off",
          "Preview only",
          "Preview + output"
        ],
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "max_resolution",
        "kind": "slider",
        "label": "Max resolution",
        "default": 4096,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 256,
        "max": 8192,
        "step": 64,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      }
    ],
    "hidden": []
  },
  "outputs": [
    {
      "name": "before",
      "type": "IMAGE"
    },
    {
      "name": "after",
      "type": "IMAGE"
    }
  ],
  "min_size": [
    320,
    420
  ],
  "family": "image"
},
  "FiLUpscaleTileCalc": {
  "id": "FiLUpscaleTileCalc",
  "title": "🔍 Upscaler Advanced",
  "category": "🎨 FiL Design/Image",
  "description": "Computes optimal tile grid layout for upscaling.",
  "inputs": {
    "required": [
      {
        "name": "upscale_factor",
        "kind": "slider",
        "label": "Upscale factor",
        "default": 2,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0.1,
        "max": 8,
        "step": 0.25,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "tile_size",
        "kind": "number",
        "label": "Tile size",
        "default": 1024,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 64,
        "max": 2048,
        "step": 64,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "tile_overlap",
        "kind": "number",
        "label": "Tile overlap",
        "default": 64,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 512,
        "step": 8,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      }
    ],
    "optional": [
      {
        "name": "auto_overlap",
        "kind": "boolean",
        "label": "Auto overlap",
        "default": false,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "advanced",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "auto_mode",
        "kind": "boolean",
        "label": "Full auto",
        "default": false,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "advanced",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "auto_profile",
        "kind": "segmented",
        "label": null,
        "default": "Balanced",
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": [
          "Low VRAM",
          "Balanced",
          "High VRAM",
          "Max Quality",
          "Ultra Quality"
        ],
        "section": "advanced",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "manual_tile_cols",
        "kind": "number",
        "label": null,
        "default": 0,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 64,
        "step": 1,
        "units": null,
        "options": null,
        "section": "advanced",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "manual_tile_rows",
        "kind": "number",
        "label": null,
        "default": 0,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 64,
        "step": 1,
        "units": null,
        "options": null,
        "section": "advanced",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "non_square_tiles",
        "kind": "boolean",
        "label": null,
        "default": false,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "advanced",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "auto_fix_thin_edges",
        "kind": "boolean",
        "label": null,
        "default": false,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "advanced",
        "visible_when": null,
        "visible_when_value": null
      }
    ],
    "hidden": []
  },
  "outputs": [
    {
      "name": "image",
      "type": "IMAGE"
    },
    {
      "name": "tiles",
      "type": "IMAGE"
    },
    {
      "name": "upscale_by",
      "type": "FLOAT"
    },
    {
      "name": "denoise",
      "type": "FLOAT"
    },
    {
      "name": "tile_width",
      "type": "INT"
    },
    {
      "name": "tile_height",
      "type": "INT"
    },
    {
      "name": "mask_blur",
      "type": "INT"
    },
    {
      "name": "tile_padding",
      "type": "INT"
    },
    {
      "name": "overlap",
      "type": "FLOAT"
    },
    {
      "name": "width",
      "type": "INT"
    },
    {
      "name": "height",
      "type": "INT"
    },
    {
      "name": "tile_cols",
      "type": "INT"
    },
    {
      "name": "tile_rows",
      "type": "INT"
    },
    {
      "name": "tile_count",
      "type": "INT"
    },
    {
      "name": "latent_w",
      "type": "INT"
    },
    {
      "name": "latent_h",
      "type": "INT"
    },
    {
      "name": "info",
      "type": "STRING"
    },
    {
      "name": "warnings",
      "type": "STRING"
    },
    {
      "name": "latent",
      "type": "LATENT"
    },
    {
      "name": "latent_tiles",
      "type": "LATENT"
    },
    {
      "name": "layout",
      "type": "DICT"
    }
  ],
  "min_size": [
    320,
    320
  ],
  "family": "image"
},
  "FiLUpscaleSimple": {
  "id": "FiLUpscaleSimple",
  "title": "🔍 Upscaler Simple",
  "category": "🎨 FiL Design/Image",
  "description": "Upscale + tile an image through a required model — same tiling controls as Advanced.",
  "inputs": {
    "required": [
      {
        "name": "upscale_factor",
        "kind": "slider",
        "label": "Upscale factor",
        "default": 2,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0.1,
        "max": 8,
        "step": 0.25,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "tile_size",
        "kind": "number",
        "label": "Tile size",
        "default": 1024,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 64,
        "max": 2048,
        "step": 64,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "tile_overlap",
        "kind": "number",
        "label": "Tile overlap",
        "default": 64,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 512,
        "step": 8,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      }
    ],
    "optional": [
      {
        "name": "auto_overlap",
        "kind": "boolean",
        "label": "Auto overlap",
        "default": false,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "advanced",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "auto_mode",
        "kind": "boolean",
        "label": "Full auto",
        "default": false,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "advanced",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "auto_profile",
        "kind": "segmented",
        "label": null,
        "default": "Balanced",
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": [
          "Low VRAM",
          "Balanced",
          "High VRAM",
          "Max Quality",
          "Ultra Quality"
        ],
        "section": "advanced",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "manual_tile_cols",
        "kind": "number",
        "label": null,
        "default": 0,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 64,
        "step": 1,
        "units": null,
        "options": null,
        "section": "advanced",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "manual_tile_rows",
        "kind": "number",
        "label": null,
        "default": 0,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 64,
        "step": 1,
        "units": null,
        "options": null,
        "section": "advanced",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "non_square_tiles",
        "kind": "boolean",
        "label": null,
        "default": false,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "advanced",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "auto_fix_thin_edges",
        "kind": "boolean",
        "label": null,
        "default": false,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "advanced",
        "visible_when": null,
        "visible_when_value": null
      }
    ],
    "hidden": []
  },
  "outputs": [
    {
      "name": "image",
      "type": "IMAGE"
    },
    {
      "name": "tiles",
      "type": "IMAGE"
    },
    {
      "name": "latent",
      "type": "LATENT"
    },
    {
      "name": "latent_tiles",
      "type": "LATENT"
    },
    {
      "name": "layout",
      "type": "DICT"
    }
  ],
  "min_size": [
    320,
    320
  ],
  "family": "image"
},
  "FiLTileAssembly": {
  "id": "FiLTileAssembly",
  "title": "🧩 Tile Assembly",
  "category": "🎨 FiL Design/Image",
  "description": "Recombines processed tiles back into one image, feathered across the real overlap zones.",
  "inputs": {
    "required": [],
    "optional": [],
    "hidden": []
  },
  "outputs": [
    {
      "name": "image",
      "type": "IMAGE"
    }
  ],
  "min_size": [
    270,
    200
  ],
  "family": "image"
},
  "FiLKSampler": {
  "id": "FiLKSampler",
  "title": "⚡ KSampler",
  "category": "🎨 FiL Design/Sampling",
  "description": "Full-featured sampler with every sampler and scheduler.",
  "inputs": {
    "required": [
      {
        "name": "seed",
        "kind": "number",
        "label": "Seed",
        "default": 0,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 18446744073709552000,
        "step": 1,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "steps",
        "kind": "number",
        "label": "Steps",
        "default": 20,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 1,
        "max": 10000,
        "step": 1,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "cfg",
        "kind": "slider",
        "label": "CFG",
        "default": 7,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 100,
        "step": 0.1,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "sampler_name",
        "kind": "combo",
        "label": "Sampler",
        "default": "euler",
        "tooltip": null,
        "values": [
          "euler"
        ],
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "scheduler",
        "kind": "combo",
        "label": "Scheduler",
        "default": "normal",
        "tooltip": null,
        "values": [
          "normal"
        ],
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "denoise",
        "kind": "slider",
        "label": "Denoise",
        "default": 1,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 1,
        "step": 0.01,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "eta",
        "kind": "slider",
        "label": "Eta (η)",
        "default": 1,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 100,
        "step": 0.01,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "bongmath",
        "kind": "boolean",
        "label": "Bongmath",
        "default": true,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "advanced",
        "visible_when": null,
        "visible_when_value": null
      }
    ],
    "optional": [
      {
        "name": "preview_method",
        "kind": "combo",
        "label": "Preview",
        "default": "auto",
        "tooltip": null,
        "values": [
          "auto",
          "latent2rgb",
          "taesd",
          "vae_decoded_only",
          "none"
        ],
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "advanced",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "vae_decode",
        "kind": "combo",
        "label": "VAE decode",
        "default": "true",
        "tooltip": null,
        "values": [
          "true",
          "true (tiled)",
          "false"
        ],
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "advanced",
        "visible_when": null,
        "visible_when_value": null
      }
    ],
    "hidden": []
  },
  "outputs": [
    {
      "name": "model",
      "type": "ANY"
    },
    {
      "name": "positive",
      "type": "ANY"
    },
    {
      "name": "negative",
      "type": "ANY"
    },
    {
      "name": "latent",
      "type": "LATENT"
    },
    {
      "name": "vae",
      "type": "ANY"
    },
    {
      "name": "image",
      "type": "IMAGE"
    }
  ],
  "min_size": [
    270,
    260
  ],
  "family": "sampling"
},
  "FiLHighResFix": {
  "id": "FiLHighResFix",
  "title": "🔬 HighRes Fix",
  "category": "🎨 FiL Design/Sampling",
  "description": "Packs latent/pixel upscale + re-sample settings into a script.",
  "inputs": {
    "required": [
      {
        "name": "upscale_type",
        "kind": "segmented",
        "label": "Upscale type",
        "default": "latent",
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": [
          "latent",
          "pixel",
          "both"
        ],
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "hires_ckpt_name",
        "kind": "combo",
        "label": "Hires checkpoint",
        "default": "(use same)",
        "tooltip": null,
        "values": [
          "(use same)"
        ],
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "latent_upscaler",
        "kind": "combo",
        "label": "Latent upscaler",
        "default": "nearest-exact",
        "tooltip": null,
        "values": [
          "nearest-exact",
          "bilinear",
          "area",
          "bicubic",
          "bislerp"
        ],
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": "upscale_type",
        "visible_when_value": "latent"
      },
      {
        "name": "pixel_upscaler",
        "kind": "combo",
        "label": "Pixel upscaler",
        "default": "(none)",
        "tooltip": null,
        "values": [
          "(none)"
        ],
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": "upscale_type",
        "visible_when_value": [
          "pixel",
          "both"
        ]
      },
      {
        "name": "upscale_by",
        "kind": "slider",
        "label": "Upscale by",
        "default": 1.25,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0.01,
        "max": 8,
        "step": 0.05,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "use_same_seed",
        "kind": "boolean",
        "label": "Use same seed",
        "default": true,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "seed",
        "kind": "number",
        "label": "Seed",
        "default": 0,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 18446744073709552000,
        "step": 1,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "hires_steps",
        "kind": "number",
        "label": "Hires steps",
        "default": 12,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 1,
        "max": 10000,
        "step": 1,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "denoise",
        "kind": "slider",
        "label": "Denoise",
        "default": 0.56,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 1,
        "step": 0.01,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "iterations",
        "kind": "number",
        "label": "Iterations",
        "default": 1,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 5,
        "step": 1,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      }
    ],
    "optional": [
      {
        "name": "use_controlnet",
        "kind": "boolean",
        "label": "Use ControlNet",
        "default": false,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "controlnet",
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "control_net_name",
        "kind": "combo",
        "label": "ControlNet",
        "default": "(none)",
        "tooltip": null,
        "values": [
          "(none)"
        ],
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "controlnet",
        "visible_when": "use_controlnet",
        "visible_when_value": true
      },
      {
        "name": "strength",
        "kind": "slider",
        "label": "Strength",
        "default": 1,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 10,
        "step": 0.01,
        "units": null,
        "options": null,
        "section": "controlnet",
        "visible_when": "use_controlnet",
        "visible_when_value": true
      },
      {
        "name": "preprocessor",
        "kind": "combo",
        "label": "Preprocessor",
        "default": "none",
        "tooltip": null,
        "values": [
          "none",
          "canny"
        ],
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": "controlnet",
        "visible_when": "use_controlnet",
        "visible_when_value": true
      }
    ],
    "hidden": []
  },
  "outputs": [
    {
      "name": "script",
      "type": "DICT"
    }
  ],
  "min_size": [
    320,
    300
  ],
  "family": "sampling"
},
  "FiLNoiseControl": {
  "id": "FiLNoiseControl",
  "title": "🎛️ Noise Control",
  "category": "🎨 FiL Design/Sampling",
  "description": "RNG source + seed-variation script for FiLKSampler.",
  "inputs": {
    "required": [
      {
        "name": "rng_source",
        "kind": "combo",
        "label": "RNG source",
        "default": "cpu",
        "tooltip": null,
        "values": [
          "cpu",
          "gpu"
        ],
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "add_seed_noise",
        "kind": "boolean",
        "label": "Seed variation",
        "default": false,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": null,
        "max": null,
        "step": null,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "seed",
        "kind": "number",
        "label": "Variation seed",
        "default": 0,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 18446744073709552000,
        "step": 1,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      },
      {
        "name": "weight",
        "kind": "slider",
        "label": "Weight",
        "default": 0.5,
        "tooltip": null,
        "values": null,
        "columns": null,
        "searchable": null,
        "min": 0,
        "max": 1,
        "step": 0.01,
        "units": null,
        "options": null,
        "section": null,
        "visible_when": null,
        "visible_when_value": null
      }
    ],
    "optional": [],
    "hidden": []
  },
  "outputs": [
    {
      "name": "script",
      "type": "DICT"
    }
  ],
  "min_size": [
    270,
    220
  ],
  "family": "sampling"
},
};

export type NodeId = keyof typeof NODE_CONTRACTS;
export const NODE_IDS: NodeId[] = Object.keys(NODE_CONTRACTS) as NodeId[];

