#!/usr/bin/env node
/**
 * Regenerate `frontend/src/api/contracts.ts` from the Pydantic node
 * contract dump produced by `scripts/dump_contracts.py` (which ships the
 * same payload as the live node_contracts endpoint, see
 * `common/brand.py`'s `ROUTE_SLUG` for the current route prefix).
 *
 * The contract layer under `common/contracts/` is the single source of
 * truth. This generator renders it into a small, hand-readable TypeScript
 * catalog that the Vue 3 + TS frontend imports for typed access to every
 * node's widget shape.
 *
 *   npm run gen:contracts
 */
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FRONTEND_DIR = resolve(__dirname, "..");
const REPO_ROOT = resolve(FRONTEND_DIR, "..");
const DUMP_SCRIPT = resolve(REPO_ROOT, "scripts", "dump_contracts.py");
const JSON_OUT = resolve(FRONTEND_DIR, "src", "api", "contracts.json");
const TS_OUT = resolve(FRONTEND_DIR, "src", "api", "contracts.ts");

function loadPayload() {
  const result = spawnSync(process.env.PYTHON || "python", [DUMP_SCRIPT], {
    cwd: REPO_ROOT,
    encoding: "utf8",
    maxBuffer: 16 * 1024 * 1024,
  });
  if (result.status !== 0 || !result.stdout) {
    console.error("[gen_contracts] python dumper failed:", result.stderr || result.stdout);
    process.exit(result.status || 1);
  }
  let payload;
  try {
    payload = JSON.parse(result.stdout);
  } catch (err) {
    console.error("[gen_contracts] could not parse dump JSON:", err);
    process.exit(1);
  }
  return payload;
}

/** The `contracts.json` text for a payload — the one place its shape is decided. */
function renderJson(payload) {
  return JSON.stringify(payload, null, 2) + "\n";
}

function renderFile(payload) {
  const out = [];
  out.push("// AUTO-GENERATED by `npm run gen:contracts`. Do not edit by hand.");
  out.push("// Source of truth: common/contracts/registry.py (Pydantic v2 models).");
  out.push("");

  // Derive WidgetKind literal union from a JSON-Schema $defs/WidgetKind entry.
  const sampleSchema = payload.schemas[Object.keys(payload.schemas)[0]] || {};
  const widgetKindEnum = sampleSchema?.$defs?.WidgetKind?.enum || [];
  out.push("export type WidgetKind =");
  if (widgetKindEnum.length) {
    out.push(widgetKindEnum.map((v) => `  | "${v}"`).join("\n") + ";");
  } else {
    out.push("  string;");
  }
  out.push("");
  out.push("export interface WidgetSpec {");
  out.push("  name: string;");
  out.push("  kind: WidgetKind;");
  out.push("  label?: string | null;");
  out.push("  default?: unknown;");
  out.push("  tooltip?: string | null;");
  out.push("  values?: string[] | null;");
  out.push("  columns?: number | null;");
  out.push("  searchable?: boolean | null;");
  out.push("  multiline?: boolean | null;");
  out.push("  min?: number | null;");
  out.push("  max?: number | null;");
  out.push("  step?: number | null;");
  out.push("  units?: string | null;");
  out.push("  options?: string[] | null;");
  out.push("  section?: string | null;");
  out.push("  visible_when?: string | null;");
  out.push("  visible_when_value?: unknown;");
  out.push("}");
  out.push("");
  out.push("export interface NodeInputs {");
  out.push("  required: WidgetSpec[];");
  out.push("  optional: WidgetSpec[];");
  out.push("  hidden: WidgetSpec[];");
  out.push("}");
  out.push("");
  out.push("export interface NodeOutput { name: string; type: string; }");
  out.push("");
  out.push("export interface NodeContract {");
  out.push("  id: string;");
  out.push("  title: string;");
  out.push("  category: string;");
  out.push("  description?: string | null;");
  out.push("  inputs: NodeInputs;");
  out.push("  outputs: NodeOutput[];");
  out.push("  min_size?: [number, number] | null;");
  out.push("  family?: string | null;");
  out.push("}");
  out.push("");
  out.push(`export const SETTINGS_PREFIX = ${JSON.stringify(payload.settings_prefix)};`);
  out.push("");
  out.push("export const NODE_CONTRACTS: Record<string, NodeContract> = {");
  const data = payload.data || {};
  for (const id of Object.keys(data)) {
    const node = data[id] || null;
    out.push(`  ${JSON.stringify(id)}: ${JSON.stringify(node, null, 2)},`);
  }
  out.push("};");
  out.push("");
  out.push("export type NodeId = keyof typeof NODE_CONTRACTS;");
  out.push("export const NODE_IDS: NodeId[] = Object.keys(NODE_CONTRACTS) as NodeId[];");
  out.push("");
  return out.join("\n");
}

/**
 * Are the committed artifacts what this checkout's contracts produce?
 *
 * Both are in git and the frontend imports them directly, so editing
 * `common/contracts/` without regenerating ships a contract the backend no
 * longer describes — and nothing else notices. The Python suite reads the
 * registry, the frontend suite reads the stale `contracts.json`, and
 * `sourceHash.mjs --check` only compares `frontend/src` against itself.
 *
 * Compared as rendered text, which is safe here precisely because both sides
 * are produced by the same `JSON.stringify`: `seed.max` arrives from Python as
 * `1.8446744073709552e+19` and is normalised to `18446744073709552000` on the
 * way in, exactly as it was when the committed file was written. Comparing the
 * raw dump against the file instead would report four differences that are the
 * same number spelled two ways. (`tests/test_contract_generation.py` guards the
 * same seam from the Python side, where the values are numbers rather than
 * text and are compared numerically.)
 */
function check(payload) {
  const stale = [];
  for (const [path, expected] of [
    [JSON_OUT, renderJson(payload)],
    [TS_OUT, renderFile(payload) + "\n"],
  ]) {
    const shown = relative(REPO_ROOT, path).split("\\").join("/");
    if (!existsSync(path)) {
      stale.push(`${shown} is missing`);
    } else if (readFileSync(path, "utf8") !== expected) {
      stale.push(`${shown} differs from what common/contracts/ produces`);
    }
  }

  if (stale.length) {
    console.error(
      `The committed contract artifacts are out of date:\n  ${stale.join("\n  ")}\n\n` +
        "They are committed and the frontend imports them directly, so this would\n" +
        "ship a contract the backend does not describe. Regenerate and commit both:\n" +
        "  npm run gen:contracts",
    );
    process.exit(1);
  }
  const count = Object.keys(payload.data || {}).length;
  console.info(`[gen_contracts] committed contracts are current (${count} contracts)`);
}

function write(payload) {
  mkdirSync(dirname(JSON_OUT), { recursive: true });
  writeFileSync(JSON_OUT, renderJson(payload), "utf8");
  mkdirSync(dirname(TS_OUT), { recursive: true });
  writeFileSync(TS_OUT, renderFile(payload) + "\n", "utf8");
  const count = Object.keys(payload.data || {}).length;
  console.info(`[gen_contracts] wrote ${TS_OUT} (${count} contracts)`);
}

const payload = loadPayload();
if (process.argv.includes("--check")) check(payload);
else write(payload);
